 name: Deploy to Server
 on:
  push:
    branches: [ main ]
  
 jobs:
   deploy:
     runs-on: ubuntu-latest 
   
     steps:
     - name: Deploy to server
       uses: appleboy/ssh-action@v0.1.5
       with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
           cd /var/www/todo-app/webstack-portfolio-project-todo-app/frontend
           git pull origin main
           npm install
           npm run build
           pm2 restart todo-frontend || pm2 start $(which npx) --name todo-frontend -- serve -s dist -l 3000
